"""Adicao da chave estrangeira em Responsavel

Revision ID: 0bfdc6f61265
Revises: e36828822f6d
Create Date: 2026-07-26 15:58:02.766746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bfdc6f61265'
down_revision = 'e36828822f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tb_responsavel', ['deleted_by'], ['responsavel_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
