"""Criar Tabela Responsavel

Revision ID: 18bbc149d9ae
Revises: 
Create Date: 2026-01-01 18:08:12.380481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bbc149d9ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_responsavel',
    sa.Column('responsavel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('responsavel_nome', sa.String(length=255), nullable=False),
    sa.Column('responsavel_siap', sa.String(length=255), nullable=False),
    sa.Column('responsavel_cpf', sa.String(length=255), nullable=False),
    sa.Column('responsavel_data_nascimento', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('responsavel_id'),
    sa.UniqueConstraint('responsavel_cpf'),
    sa.UniqueConstraint('responsavel_siap')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_responsavel')
    # ### end Alembic commands ###
