"""Modificacao nos campos SIAP e CPF em Responsavel

Revision ID: 29ac8064bde8
Revises: 604a5e88cca1
Create Date: 2026-04-15 19:44:30.822310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ac8064bde8'
down_revision = '604a5e88cca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_usuario',
    sa.Column('usuario_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('funcao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.alter_column('responsavel_siap',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=7),
               existing_nullable=True)
        batch_op.alter_column('responsavel_cpf',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.alter_column('responsavel_cpf',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('responsavel_siap',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    op.drop_table('tb_usuario')
    # ### end Alembic commands ###
