"""Adicao da chave estrangeira em Retirada

Revision ID: 35360492060d
Revises: 0bfdc6f61265
Create Date: 2026-07-26 16:38:18.074225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35360492060d'
down_revision = '0bfdc6f61265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_reserva', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tb_responsavel', ['deleted_by'], ['responsavel_id'])

    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tb_responsavel_deleted_by_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('tb_responsavel_deleted_by_fkey'), 'tb_responsavel', ['deleted_by'], ['responsavel_id'])

    with op.batch_alter_table('tb_reserva', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
