"""Modificacao na Tabela Chaves no campo chave_nome

Revision ID: 604a5e88cca1
Revises: cd1662cb70e6
Create Date: 2026-03-27 10:48:29.946753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604a5e88cca1'
down_revision = 'cd1662cb70e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.alter_column('responsavel_siap',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.alter_column('responsavel_siap',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
