"""adicao da tabela chave

Revision ID: 71726c1f89b8
Revises: f8c802ea7c29
Create Date: 2026-01-06 13:48:51.097631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71726c1f89b8'
down_revision = 'f8c802ea7c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_chave',
    sa.Column('chave_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chave_nome', sa.String(length=255), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sala_id'], ['tb_sala.sala_id'], ),
    sa.PrimaryKeyConstraint('chave_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_chave')
    # ### end Alembic commands ###
