"""Adicao do campo deleted_by em sala

Revision ID: 77956c8df186
Revises: 912add8d90c6
Create Date: 2026-07-24 09:51:17.298992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77956c8df186'
down_revision = '912add8d90c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_sala', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_sala', schema=None) as batch_op:
        batch_op.drop_column('deleted_by')

    # ### end Alembic commands ###
