"""Adicao do campo Matricula em Responsavel

Revision ID: 8e036b76c530
Revises: f54dad124c5a
Create Date: 2026-06-24 11:15:56.623228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e036b76c530'
down_revision = 'f54dad124c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel_matricula', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.drop_column('responsavel_matricula')

    # ### end Alembic commands ###
