"""modificacao em Salas

Revision ID: 912add8d90c6
Revises: 8e036b76c530
Create Date: 2026-07-23 14:32:39.030163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912add8d90c6'
down_revision = '8e036b76c530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_sala', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_sala', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
