"""adicao da tabela reserva

Revision ID: 9b01d9166469
Revises: 71726c1f89b8
Create Date: 2026-01-12 08:52:07.448321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b01d9166469'
down_revision = '71726c1f89b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_reserva',
    sa.Column('reserva_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('frequencia', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_id'], ['tb_responsavel.responsavel_id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['tb_sala.sala_id'], ),
    sa.PrimaryKeyConstraint('reserva_id')
    )
    op.create_table('tb_reserva_dia',
    sa.Column('reserva_dia_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['tb_reserva.reserva_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reserva_dia_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_reserva_dia')
    op.drop_table('tb_reserva')
    # ### end Alembic commands ###
