"""Adicao de chave estrangeira em Sala

Revision ID: 9ef5f4ce588e
Revises: ae9b0e76db7f
Create Date: 2026-07-26 15:01:58.515614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef5f4ce588e'
down_revision = 'ae9b0e76db7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_sala', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tb_responsavel', ['deleted_by'], ['responsavel_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_sala', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
