"""adicao da tabela retirada

Revision ID: a5e81fe533eb
Revises: 9b01d9166469
Create Date: 2026-02-01 13:45:32.355060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e81fe533eb'
down_revision = '9b01d9166469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_retirada',
    sa.Column('retirada_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chave_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=True),
    sa.Column('data_retirada', sa.Date(), nullable=False),
    sa.Column('hora_retirada', sa.Time(), nullable=False),
    sa.Column('hora_prevista_devolucao', sa.Time(), nullable=False),
    sa.Column('hora_devolucao', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['chave_id'], ['tb_chave.chave_id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['tb_reserva.reserva_id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['tb_responsavel.responsavel_id'], ),
    sa.PrimaryKeyConstraint('retirada_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_retirada')
    # ### end Alembic commands ###
