"""Adicao da chave estrangeira em Retiradas 2

Revision ID: dc5b850fea9c
Revises: fd0e342dd87f
Create Date: 2026-07-26 18:40:07.299758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5b850fea9c'
down_revision = 'fd0e342dd87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_retirada', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tb_responsavel', ['deleted_by'], ['responsavel_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_retirada', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
