"""Adicao da chave estrangeira em Chave

Revision ID: e36828822f6d
Revises: 9ef5f4ce588e
Create Date: 2026-07-26 15:31:21.966157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36828822f6d'
down_revision = '9ef5f4ce588e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_chave', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tb_responsavel', ['deleted_by'], ['responsavel_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_chave', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
