"""add email, senha e funcao em tb_responsavel

Revision ID: f54dad124c5a
Revises: 29ac8064bde8
Create Date: 2026-06-22 17:17:29.036484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54dad124c5a'
down_revision = '29ac8064bde8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_usuario')
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('senha', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('funcao', sa.String(length=255), nullable=False))
        batch_op.alter_column('responsavel_siap',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=7),
               existing_nullable=True)
        batch_op.alter_column('responsavel_cpf',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=14),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_responsavel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('responsavel_cpf',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('responsavel_siap',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('funcao')
        batch_op.drop_column('senha')
        batch_op.drop_column('email')

    op.create_table('tb_usuario',
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('funcao', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('usuario_id', name=op.f('tb_usuario_pkey')),
    sa.UniqueConstraint('email', name=op.f('tb_usuario_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
