"""Adição da Tabela Sala

Revision ID: f8c802ea7c29
Revises: 18bbc149d9ae
Create Date: 2026-01-05 16:05:13.485696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c802ea7c29'
down_revision = '18bbc149d9ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_sala',
    sa.Column('sala_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sala_nome', sa.String(length=255), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('sala_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_sala')
    # ### end Alembic commands ###
