"""Adicao da chave estrangeira em Retiradas

Revision ID: fd0e342dd87f
Revises: 35360492060d
Create Date: 2026-07-26 17:50:17.861457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0e342dd87f'
down_revision = '35360492060d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_retirada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_devolucao', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_retirada', schema=None) as batch_op:
        batch_op.drop_column('data_devolucao')

    # ### end Alembic commands ###
